#!/bin/bash

# Check that the game is up-to-date
steamcmd \
    @ShutdownOnFailedCommand \
    @NoPromptForPassword \
    +login anonymous \
    +force_install_dir ${STEAMAPPDIR} \
    +app_update ${STEAMAPPID} \
    +'quit'

# Update settings.xml using ENV varaibles
SETTINGS_XML=${STEAMAPPDIR}/serversettings.xml

# serversettings.xml is only generated by the server itself on first run.
# If it's missing, do a throwaway run just to let the server create it with
# default values, then kill it before it finishes starting.
if [ ! -f "${SETTINGS_XML}" ]; then
    echo "serversettings.xml not found, running DedicatedServer once to generate defaults..."

    BOOTSTRAP_LOG=$(mktemp)
    "${STEAMAPPDIR}"/DedicatedServer >"${BOOTSTRAP_LOG}" 2>&1 &
    BOOTSTRAP_PID=$!

    tail -n +1 -f "${BOOTSTRAP_LOG}" &
    TAIL_PID=$!

    BOOTSTRAP_TIMEOUT=60
    waited=0
    while ! grep -qF 'WARNING: File "serversettings.xml" not found. Starting the server with default settings.' "${BOOTSTRAP_LOG}"; do
        if ! kill -0 "${BOOTSTRAP_PID}" 2>/dev/null; then
            echo "DedicatedServer exited before generating serversettings.xml"
            kill "${TAIL_PID}" 2>/dev/null
            wait "${TAIL_PID}" 2>/dev/null
            exit 1
        fi
        if [ "${waited}" -ge "${BOOTSTRAP_TIMEOUT}" ]; then
            echo "Timed out waiting for DedicatedServer to generate serversettings.xml"
            kill "${BOOTSTRAP_PID}" 2>/dev/null
            kill "${TAIL_PID}" 2>/dev/null
            wait "${TAIL_PID}" 2>/dev/null
            exit 1
        fi
        sleep 1
        waited=$((waited + 1))
    done

    # Stop the throwaway server, giving it a chance to shut down cleanly first
    kill "${BOOTSTRAP_PID}" 2>/dev/null
    for _ in $(seq 1 10); do
        kill -0 "${BOOTSTRAP_PID}" 2>/dev/null || break
        sleep 1
    done
    kill -9 "${BOOTSTRAP_PID}" 2>/dev/null
    wait "${BOOTSTRAP_PID}" 2>/dev/null

    kill "${TAIL_PID}" 2>/dev/null
    wait "${TAIL_PID}" 2>/dev/null
    rm -f "${BOOTSTRAP_LOG}"
fi

sed -i "s/password=.*/password=\"${BAR_PASSWORD}\"/" "${SETTINGS_XML}"
sed -i "s/ServerName=.*/ServerName=\"${BAR_NAME}\"/" "${SETTINGS_XML}"
sed -i "s/ServerMessageText=.*/ServerMessageText=\"${BAR_SERVERMESSAGE}\"/" "${SETTINGS_XML}"
sed -i "s/StartWhenClientsReady=.*/StartWhenClientsReady=\"${BAR_START_WHEN_CLIENTS_READY}\"/" "${SETTINGS_XML}"
sed -i "s/StartWhenClientsReadyRatio=.*/StartWhenClientsReadyRatio=\"${BAR_START_WHEN_CLIENTS_READY_RATIO}\"/" "${SETTINGS_XML}"
sed -i "s/IsPublic=.*/IsPublic=\"true\"/" "${SETTINGS_XML}"

# Create client Permissions
# <Name>:<SteamID>:<Permissions>:<Commands>
# <InGameName1>:<SteamID1>:<Permission1.1>,<Permission1.2>,<Permission1.3>:<Command1.1>,<Command1.2>;<InGameName2>:<SteamID2>:<Permission2.1>,<Permission2.2>;<InGameName3>:<SteamID3>:<Permission3.1>:<Command3.1>,<Command3.2>;
# Commands are optional
CLIENT_PERMISSIONS_XML=${STEAMAPPDIR}/Data/clientpermissions.xml
echo \
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>
<ClientPermissions>" \
    >"$CLIENT_PERMISSIONS_XML"

IFS=$";"
for client_permission in ${BAR_PERMISSIONS}; do
    IFS=$":"
    client_permission_terms=($client_permission)

    name=${client_permission_terms[0]}
    steamid=${client_permission_terms[1]}
    permissions=${client_permission_terms[2]}
    commands=${client_permission_terms[3]}

    echo "  <Client name=\"${name}\" steamid=\"${steamid}\" permissions=\"${permissions}\">" >>"$CLIENT_PERMISSIONS_XML"

    IFS=$","
    for command in ${commands}; do
        echo "    <command name=\"${command}\"/>" >>"$CLIENT_PERMISSIONS_XML"
    done

    echo "  </Client>" >>"$CLIENT_PERMISSIONS_XML"
done

echo "</ClientPermissions>" >>"$CLIENT_PERMISSIONS_XML"

# Run the server!
"${STEAMAPPDIR}"/DedicatedServer
